/** @type {import('tailwindcss').Config} */
// GENERATED by scripts/tailwind-precompile.py - rerun that rather than hand-editing.
// Build: <tailwindcss> -c tailwind.config.js -i src/input.css -o styles.css --minify
// Replaces the runtime cdn.tailwindcss.com JIT compiler with a precompiled stylesheet.
// Any class added to this site LATER needs a rebuild or it will not exist in the CSS.
module.exports = {
    theme: {
      extend: {
        colors: {
          navy: {
            "50": "#eaeaf2",
            "100": "#cbcbdf",
            "200": "#a8a9c9",
            "300": "#8587b3",
            "400": "#6a6da2",
            "500": "#505391",
            "600": "#474a86",
            "700": "#3b3e77",
            "800": "#303368",
            "900": "#2a2d61",
            "950": "#232650",
          },
          gold: {
            "300": "#e8485a",
            "400": "#d92a3e",
            "500": "#c8102e",
            "600": "#a00d25",
          },
          accent: {
            "500": "#c8102e",
            "600": "#a00d25",
            "700": "#80091c",
          },
        },
        fontFamily: {
          heading: ["Oswald", "sans-serif"],
          body: ["Inter", "sans-serif"],
        },
      },
    },
    content: ["./*.html"],
  }
